import type { Request, Response } from "express";
import { CourseLevel } from "../generated/prisma/enums.js";
import type { AuthRequest } from "../auth/auth.types.js";
import { assertStudentAccess, getRequestScope } from "../auth/accessScope.js";
import * as service from "./exam.service.js";
const param=(req:Request,key:string)=>{const value=req.params[key];return Array.isArray(value)?value[0]:value;};
export const submit=async(req:AuthRequest,res:Response)=>{const result=await service.submitExam(req.body,await getRequestScope(req.auth?.id));res.status(result.statusCode).json({success:true,data:result.data});};
export const list=async(req:AuthRequest,res:Response)=>res.json({success:true,data:await service.listExams(req.query,await getRequestScope(req.auth?.id))});
export const get=async(req:AuthRequest,res:Response)=>res.json({success:true,data:await service.getExam(param(req,"id"),await getRequestScope(req.auth?.id))});
export const studentHistory=async(req:AuthRequest,res:Response)=>{const scope=await getRequestScope(req.auth?.id);await assertStudentAccess(scope,param(req,"studentId"));res.json({success:true,data:await service.getStudentExamHistory(param(req,"studentId"),req.query)});};
export const studentLatest=async(req:AuthRequest,res:Response)=>{const scope=await getRequestScope(req.auth?.id);await assertStudentAccess(scope,param(req,"studentId"));res.json({success:true,data:await service.getLatestStudentExam(param(req,"studentId"))});};
export const studentCourseResults=async(req:AuthRequest,res:Response)=>{const scope=await getRequestScope(req.auth?.id);await assertStudentAccess(scope,param(req,"studentId"));res.json({success:true,data:await service.getStudentCourseExamResults(param(req,"studentId"))});};
export const rules=async(_req:Request,res:Response)=>res.json({success:true,data:await service.listActiveExamRules()});
export const rule=async(req:Request,res:Response)=>{const level=param(req,"courseLevel") as CourseLevel;if(!Object.values(CourseLevel).includes(level))return res.status(404).json({success:false,message:"Exam rule not found"});return res.json({success:true,data:await service.getActiveExamRule(level)});};
