CREATE TYPE "CourseLevel" AS ENUM ('MAKTAB_STAGE_1','MAKTAB_STAGE_2','MAKTAB_STAGE_3','NAZIRAH_STAGE_1','NAZIRAH_STAGE_2','NAZIRAH_STAGE_3','NAZIRAH_STAGE_4','HIFZ_STAGE_1','HIFZ_STAGE_2','HIFZ_STAGE_3','HIFZ_STAGE_4');
CREATE TYPE "ExamStatus" AS ENUM ('DRAFT','SUBMITTED','VOIDED');
CREATE TYPE "ExamOutcome" AS ENUM ('PASSED','NEEDS_IMPROVEMENT');
CREATE TYPE "PromotionReason" AS ENUM ('EXAM_PASSED','MANUAL_ADJUSTMENT');
ALTER TABLE "Student" ADD COLUMN "currentCourseLevel" "CourseLevel", ADD COLUMN "courseCompleted" BOOLEAN NOT NULL DEFAULT false, ADD COLUMN "courseUpdatedAt" TIMESTAMP(3);

-- Conservatively map only recognizable existing course/stage pairs. Unmapped rows remain NULL for review.
UPDATE "Student" SET "currentCourseLevel" = CASE
 WHEN lower(coalesce("courseName",'')) LIKE '%maktab%' AND lower(coalesce("courseStage",'')) ~ '(stage )?1' THEN 'MAKTAB_STAGE_1'::"CourseLevel"
 WHEN lower(coalesce("courseName",'')) LIKE '%maktab%' AND lower(coalesce("courseStage",'')) ~ '(stage )?2' THEN 'MAKTAB_STAGE_2'::"CourseLevel"
 WHEN lower(coalesce("courseName",'')) LIKE '%maktab%' AND lower(coalesce("courseStage",'')) ~ '(stage )?3' THEN 'MAKTAB_STAGE_3'::"CourseLevel"
 WHEN lower(coalesce("courseName",'')) LIKE 'nazi%' AND lower(coalesce("courseStage",'')) ~ '(stage )?1' THEN 'NAZIRAH_STAGE_1'::"CourseLevel"
 WHEN lower(coalesce("courseName",'')) LIKE 'nazi%' AND lower(coalesce("courseStage",'')) ~ '(stage )?2' THEN 'NAZIRAH_STAGE_2'::"CourseLevel"
 WHEN lower(coalesce("courseName",'')) LIKE 'nazi%' AND lower(coalesce("courseStage",'')) ~ '(stage )?3' THEN 'NAZIRAH_STAGE_3'::"CourseLevel"
 WHEN lower(coalesce("courseName",'')) LIKE 'nazi%' AND lower(coalesce("courseStage",'')) ~ '(stage )?4' THEN 'NAZIRAH_STAGE_4'::"CourseLevel"
 WHEN lower(coalesce("courseName",'')) LIKE '%hifz%' AND lower(coalesce("courseStage",'')) ~ '(stage )?1' THEN 'HIFZ_STAGE_1'::"CourseLevel"
 WHEN lower(coalesce("courseName",'')) LIKE '%hifz%' AND lower(coalesce("courseStage",'')) ~ '(stage )?2' THEN 'HIFZ_STAGE_2'::"CourseLevel"
 WHEN lower(coalesce("courseName",'')) LIKE '%hifz%' AND lower(coalesce("courseStage",'')) ~ '(stage )?3' THEN 'HIFZ_STAGE_3'::"CourseLevel"
 WHEN lower(coalesce("courseName",'')) LIKE '%hifz%' AND lower(coalesce("courseStage",'')) ~ '(stage )?4' THEN 'HIFZ_STAGE_4'::"CourseLevel" END
WHERE "currentCourseLevel" IS NULL;

CREATE TABLE "ExamAttempt" ("id" TEXT NOT NULL,"studentId" TEXT NOT NULL,"examinerId" TEXT NOT NULL,"courseLevel" "CourseLevel" NOT NULL,"status" "ExamStatus" NOT NULL DEFAULT 'SUBMITTED',"outcome" "ExamOutcome" NOT NULL,"totalScore" INTEGER NOT NULL,"totalMaxScore" INTEGER NOT NULL,"percentage" DECIMAL(5,2) NOT NULL,"attemptNumber" INTEGER NOT NULL,"notes" TEXT,"idempotencyKey" TEXT NOT NULL,"createdById" TEXT,"submittedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "ExamAttempt_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ExamMark" ("id" TEXT NOT NULL,"examAttemptId" TEXT NOT NULL,"fieldKey" TEXT NOT NULL,"label" TEXT NOT NULL,"description" TEXT,"obtainedMarks" INTEGER NOT NULL,"maximumMarks" INTEGER NOT NULL,"sectionKey" TEXT NOT NULL,"sortOrder" INTEGER NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "ExamMark_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ExamSectionResult" ("id" TEXT NOT NULL,"examAttemptId" TEXT NOT NULL,"sectionKey" TEXT NOT NULL,"sectionLabel" TEXT NOT NULL,"obtainedMarks" INTEGER NOT NULL,"maximumMarks" INTEGER NOT NULL,"passingMarks" INTEGER NOT NULL,"passed" BOOLEAN NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "ExamSectionResult_pkey" PRIMARY KEY ("id"));
CREATE TABLE "StudentCourseHistory" ("id" TEXT NOT NULL,"studentId" TEXT NOT NULL,"fromLevel" "CourseLevel","toLevel" "CourseLevel" NOT NULL,"examAttemptId" TEXT,"reason" "PromotionReason" NOT NULL,"changedById" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "StudentCourseHistory_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "ExamAttempt_idempotencyKey_key" ON "ExamAttempt"("idempotencyKey"); CREATE UNIQUE INDEX "ExamAttempt_studentId_courseLevel_attemptNumber_key" ON "ExamAttempt"("studentId","courseLevel","attemptNumber"); CREATE INDEX "ExamAttempt_studentId_submittedAt_idx" ON "ExamAttempt"("studentId","submittedAt"); CREATE INDEX "ExamAttempt_examinerId_idx" ON "ExamAttempt"("examinerId"); CREATE INDEX "ExamAttempt_courseLevel_outcome_idx" ON "ExamAttempt"("courseLevel","outcome");
CREATE UNIQUE INDEX "ExamMark_examAttemptId_fieldKey_key" ON "ExamMark"("examAttemptId","fieldKey"); CREATE INDEX "ExamMark_examAttemptId_idx" ON "ExamMark"("examAttemptId"); CREATE UNIQUE INDEX "ExamSectionResult_examAttemptId_sectionKey_key" ON "ExamSectionResult"("examAttemptId","sectionKey"); CREATE INDEX "ExamSectionResult_examAttemptId_idx" ON "ExamSectionResult"("examAttemptId"); CREATE UNIQUE INDEX "StudentCourseHistory_examAttemptId_key" ON "StudentCourseHistory"("examAttemptId"); CREATE INDEX "StudentCourseHistory_studentId_createdAt_idx" ON "StudentCourseHistory"("studentId","createdAt");
ALTER TABLE "ExamAttempt" ADD CONSTRAINT "ExamAttempt_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "Student"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "ExamAttempt" ADD CONSTRAINT "ExamAttempt_examinerId_fkey" FOREIGN KEY ("examinerId") REFERENCES "Teacher"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "ExamAttempt" ADD CONSTRAINT "ExamAttempt_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ExamMark" ADD CONSTRAINT "ExamMark_examAttemptId_fkey" FOREIGN KEY ("examAttemptId") REFERENCES "ExamAttempt"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "ExamSectionResult" ADD CONSTRAINT "ExamSectionResult_examAttemptId_fkey" FOREIGN KEY ("examAttemptId") REFERENCES "ExamAttempt"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "StudentCourseHistory" ADD CONSTRAINT "StudentCourseHistory_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "Student"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "StudentCourseHistory" ADD CONSTRAINT "StudentCourseHistory_examAttemptId_fkey" FOREIGN KEY ("examAttemptId") REFERENCES "ExamAttempt"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "StudentCourseHistory" ADD CONSTRAINT "StudentCourseHistory_changedById_fkey" FOREIGN KEY ("changedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
